apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: nginx-exporter
    spec:
      containers:
      - args:
        - --nginx.scrape_uri=http://localhost/nginx/status
        name: nginx-exporter
        image: fish/nginx-exporter
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 25M
        livenessProbe:
          httpGet: 
            path: /~/healthy
            port: 9113
