apiVersion: v1
kind: Pod
metadata:
  name: testaroo
  labels:
    app: testapp
spec:
  containers:
  - name: test-container
    image: jaded-seeker:latest
    ports:
    - containerPort: 80
    imagePullPolicy: Never
