apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      labels:
        app: statsd-exporter
    spec:
      containers:
      - name: statsd-exporter
        image: prom/statsd-exporter:v0.18.0
        ports:
        - containerPort: 9102
        - containerPort: 9125
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter-svc
  labels:
    app: statsd-exporter
spec:
  ports:
  - name: udp
    port: 9125 #port to push metrics to
    protocol: UDP
    targetPort: 9125
  - name: tcp
    port: 9102 #port to fetch metrics from
    protocol: TCP
    targetPort: 9102
  selector:
    app: statsd-exporter