apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-volume-claim
  labels:
    app: postgres
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pg-volume
