apiVersion: v1
kind: Pod
metadata:
  name: pg-pod
spec:
  volumes:
    - name: pg-storage
      persistentVolumeClaim:
        claimName: pg-volume-claim
  containers:
    - name: pg-container
      image: postgres:9.6.16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-credential
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credential
              key: password
        - name: POSTGRES_DB
          value: cyclops_db
      volumeMounts:
        - name: pg-storage
          mountPath: /var/lib/postgresql/data
