kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-pervol
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/folders/pgdata/pg-pv


